### PR TITLE
Cgspace discussion2

### PR DESCRIPTION
**Pull request by marieALaporte**

### CODE REVIEW

**Comment by marieALaporte** [comment]
@alanorth I was not sure if I should remove cg:note or not based on #2

**Comment by alanorth** [comment]
@marieALaporte this is great work. For `cg:note`, if it's OK with you I think we should keep using `dct:description` because CGSpace is already using `dc:description` (with 16,000 occurrences of this field right now). We store miscellaneous notes related to the resource there, for example:

- `Disponible à la FAO, Service AGSM, Via delle Terme di Caracalla, 00100 Rome - ITALIE`
- `Originally published in 1975, the 1986 edition of the Appropriate Technology Sourcebook contains...`
- `Version électronique sur le site Web : http://www.fao.org`

**Comment by marieALaporte** [comment]
@alanorth it's ok if you continue using it for now, but on the long run, it would be great if you could move them. That can come later, there is no hurry for that. 

In order to not create confusion with what is currently recommended for the datasets, I would prefer not to add it to the guidelines though. Hoping that is fine

**Comment by alanorth** [comment]
OK, we will keep using `dct:description` on CGSpace for now. As I understand the [DCMI terms comment](http://www.dublincore.org/specifications/dublin-core/dcmi-terms/#terms-description), a "free-text description of the resource" is relevant for all item types, not just Datasets.

**Comment by marieALaporte** [comment]
@alanorth coming back on CG Core after summer break. I think this is ready to merge, right?

**Comment by alanorth** [comment]
Hi @marieALaporte. I'm so sorry, I have been busy with other stuff the past few weeks and haven't finished testing the new schema implementation on the CGSpace test environment. We are all in agreement in theory (and I've even been discussing with ICARDA for MELSpace), so I think you should merge the changes. If run into DSpace-specific issues with any of the fields in the implementation I will file an issue here.

Thanks!

**Comment by alanorth** [comment]
Update: it seems that the following fields are hard coded deep in the Java core of DSpace and we can't change them without getting dirty:

- dc.title→dcterms.title
- dc.title.alternative→dcterms.alternative
- dc.contributor.author→dcterms.creator

So CGSpace will not be able to adopt those particular parts of CG Core v2 due to technical limitations. It is safe to assume that other DSpace installations like CIMMYT, MELSpace, CIFOR, and WorldFish will not be able to either. I'm keeping my [implementation notes and progress updated](https://gist.github.com/alanorth/2db39e91f48d116e00a4edffd6ba6409).

**Pull request merged**
